### ISSUE TITLE
Doesn't work with msx format

### ISSUE THREAD

**Issue by jduyon** [happyleavesaoc/aoc-mgz#1]
I've tried to run it against the new .msx (AOE2HD) files and have had no luck. I guess that's obvious since it's intended to work against mgz files, but do you have any tips for figuring out the new max format?

**Comment by happyleavesaoc** [comment]
recanalyst (listed under Resources in the readme) has some code to handle HD recorded games. I'd start there. I don't think the changes are significant.

**Comment by happyleavesaoc** [comment]
Fixed in https://github.com/happyleavesaoc/aoc-mgz/commit/91acd3732d4fd654b18c8076bf7b0f09c654f966
