### ISSUE TITLE
Some questions about structure.

### ISSUE THREAD

**Issue by cute-cirno** [happyleavesaoc/aoc-mgz#105]
Dear Author,

I am very interested in your project. While using the commit from the PR and loading the latest version of the recordings, I found that the tile_format seems to be outdated. I modified it from 'bxb6x' to 'bxb7x', which appears to align the structure correctly. However, I am unsure if the first byte in 7x is necessary. Could you please clarify this?

Thank you.
![image](https://github.com/user-attachments/assets/f987ff65-4474-4e97-a65e-c1819332bd40)

**Comment by happyleavesaoc** [comment]
Hello, DE version `62.0` adds an extra byte in index `1`. This is accounted for in `mgz-1.8.26`, @ https://github.com/happyleavesaoc/aoc-mgz/commit/8fb99691cd2508e0f36e17a67a198ee77a1f75e1
