### ISSUE TITLE
No postgame detected for any DE matches?

### ISSUE THREAD

**Issue by heitorbffi** [happyleavesaoc/aoc-mgz#18]
I have tested this with many 2x2 online DE matches, and get_postgame always returns None, even though matches completed (i.e., get_completed returns True) irrespective of whether I resigned, enemies resigned, I was party leader, or someone else was. 
May I be missing something? 

My intention is to be able to list how much of each resource each player got by the end of the match, age advancement times, etc., and as I see it that kind of info is offered by get_players, which depends on get_postgame not being None. 

Let me know if I can provide any further info or offer any specific help!

**Comment by happyleavesaoc** [comment]
There is no postgame for DE matches. That is a Userpatch feature.

**Comment by heitorbffi** [comment]
So is there a way to obtain info on how much of each resource each player got by the end of the match, age advancement times, etc., for DE matches with aoc-mgz?

**Comment by happyleavesaoc** [comment]
There's no way from the rec alone. You'd have to replay the match and examine the game memory.

**Comment by happyleavesaoc** [comment]
Btw, I placed a request for this feature in the official DE forums back in December. Perhaps add your support: https://forums.ageofempires.com/t/suggestion-append-achievements-to-recorded-game-file/64800

**Comment by heitorbffi** [comment]
Thanks! Will do.
