### ISSUE TITLE
Playing back aoe2record files

### ISSUE THREAD

**Issue by diogoalmeida** [happyleavesaoc/aoc-mgz#20]
Hi,

Apologies if this is obvious, but it is not clear to me what should I run when trying to playback a `aoe2record` file. I use the cli script as 

```
python3 mgz/cli.py play myfile.aoe2record
```
to which I get

```
INFO:mgz.summary:parsed header in 6.56 seconds
INFO:mgz.summary:parsed body in 1.40 seconds
INFO:mgz.playback:trying to connect @ ws://
INFO:mgz.playback:trying again to connect ...
INFO:mgz.playback:trying again to connect ...
INFO:mgz.playback:trying again to connect ...
INFO:mgz.playback:trying again to connect ...
INFO:mgz.playback:trying again to connect ...
ERROR:mgz.playback:failed to launch playback
```
What is supposed to be running at this stage? Is that an instance of [aoc-headless](https://github.com/happyleavesaoc/aoc-headless)? In that case, is there any hope for this to work with a definitive edition replay? 

Thank you so much for your time!

**Comment by happyleavesaoc** [comment]
Hi there, playback is not supported for DE.
