### ISSUE TITLE
achievements parsing for DE returning null results 

### ISSUE THREAD

**Issue by gregstein** [happyleavesaoc/aoc-mgz#21]
Hello Happyleaves,

 `get_players()` for DE summary seem to return None for most entries:

`[{'name': 'Fur_27', 'civilization': 6, 'human': True, 'number': 1, 'color_id': 2, 'winner': False, 'mvp': None, 'score': None, 'position': (97.0, 56.0), 'rate_snapshot': None, 'user_id': 403294, 'cheater': False, 'achievements': {'military': {'score': None, 'units_killed': None, 'hit_points_killed': None, 'units_lost': None, 'buildings_razed': None, 'hit_points_razed': None, 'buildings_lost': None, 'units_converted': None}, 'economy': {'score': None, 'food_collected': None, 'wood_collected': None, 'stone_collected': None, 'gold_collected': None, 'tribute_sent': None, 'tribute_received': None, 'trade_gold': None, 'relic_gold': None}, 'technology': {'score': None, 'feudal_time': None, 'castle_time': None, 'imperial_time': None, 'explored_percent': None, 'research_count': None, 'research_percent': None}, 'society': {'score': None, 'total_wonders': None, 'total_castles': None, 'total_relics': None, 'villager_high': None}}}, {'name': '[the][big][one]', 'civilization': 6, 'human': True, 'number': 2, 'color_id': 0, 'winner': True, 'mvp': None, 'score': None, 'position': (12.0, 59.0), 'rate_snapshot': None, 'user_id': 1228905, 'cheater': False, 'achievements': {'military': {'score': None, 'units_killed': None, 'hit_points_killed': None, 'units_lost': None, 'buildings_razed': None, 'hit_points_razed': None, 'buildings_lost': None, 'units_converted': None}, 'economy': {'score': None, 'food_collected': None, 'wood_collected': None, 'stone_collected': None, 'gold_collected': None, 'tribute_sent': None, 'tribute_received': None, 'trade_gold': None, 'relic_gold': None}, 'technology': {'score': None, 'feudal_time': None, 'castle_time': None, 'imperial_time': None, 'explored_percent': None, 'research_count': None, 'research_percent': None}, 'society': {'score': None, 'total_wonders': None, 'total_castles': None, 'total_relics': None, 'villager_high': None}}}]`

is it a bug or are you still working on it?

And thanks btw big fan of this library <3

**Comment by goto-bus-stop** [comment]
achievements data is not stored in DE recs.

**Comment by gregstein** [comment]
That was some ultra fast response. Thank you!! Is there a way to retrieve those from api or something ?

**Comment by happyleavesaoc** [comment]
Not that I know of. Sorry about that!

**Comment by gregstein** [comment]
Thank you! Still love this amazing library. I was hoping if you can send me a birthday present in a zip format and when I open it.. "Wooow! It's happyleaves mgz lib <3"
