### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Overconfidence** [happyleavesaoc/aoc-mgz#26]
Hi!
I found your program yesterday when I was looking around the net to figure out the structure of AoE2DE's replays. I immediately downloaded it and tried to figure out how this works, but I'm very new to this thing, so I would like to ask some questions:
Is there some kind of tutorial/documentation how to use this program?
Can I use it to convert the starting state of the game and the player's action into an .xml or .csv file?
Sorry, if it's not the right place to ask, and thank you for your work.

**Comment by happyleavesaoc** [comment]
The only documentation is in the readme file. Usage will require knowledge of programming and specifically Python.

You can use this to converting to XML or CSV, though you'd have to define the target format and write the transform yourself.
