### ISSUE TITLE
Is possible to extract  real time information?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [happyleavesaoc/aoc-mgz#4]
Hi! I'm trying to build something that allows me to get real time information like K/D, and other stats, but right now it has been kinda hard to extract these from the recording as it only records the actions performed by users. Is this possible to do with this parser?

What I can deduct is that will be impossible without simulating the entire game, but I might be wrong. I have found some information that reads directly from game memory, that is something that I want to avoid as is not an easy task to perform.

Any advice will be appreciated

**Comment by coffenbacher** [comment]
I think your best bet is to discuss on the AIScipters forum, probably with Scripter64 http://forums.aiscripters.com/memberlist.php?mode=viewprofile&u=822 (also available on reddit as https://www.reddit.com/user/scripter16)

I don't know if it's possible to parse the rec file in a streaming fashion, but the way the spectator overlays work on Voobly is to expose that information from the game itself

**Comment by goto-bus-stop** [comment]
> What I can deduct is that will be impossible without simulating the entire game, but I might be wrong.

Unfortunately you're not wrong. For K/D specifically, it's impossible to determine whether a unit died or even whether units finished training from recorded games alone. Only the actions taken by a player are recorded; none of the consequences of those actions are.

At the very end of multiplayer games, UserPatch records the achievements data block. That gives the information that you can see on Voobly match pages and such. You can use the `rec.summarize()` method of this package to get that information. But that's not exactly realtime!
