### ISSUE TITLE
Summary reports wrong starting age

### ISSUE THREAD

**Issue by gethvi** [happyleavesaoc/aoc-mgz#54]
Collecting Summary on a regular ranked 1v1 RM match returns `'starting_age': (2, 'castle')` which is obviously wrong.

Version: `(<Version.DE: 21>, 'VER 9.4', 20.06, 5)`

[AgeIIDE_Replay_85017375.zip](https://github.com/happyleavesaoc/aoc-mgz/files/6353151/AgeIIDE_Replay_85017375.zip)

Using the latest version of aoc-mgz from pip.

**Comment by happyleavesaoc** [comment]
DE uses a different age enumeration, it seems. In AoC, `2` is `castle` but in DE, `4` is `castle`, etc. I would like to keep the returned IDs consistent so for now, in https://github.com/happyleavesaoc/aoc-mgz/commit/2f6e5d9aba47b55849527affa425916394197fdc, I've remapped the DE IDs by subtracting 2.
