### ISSUE TITLE
Question: AOC_PLAYBACK

### ISSUE THREAD

**Issue by zorrodg** [happyleavesaoc/aoc-mgz#56]
Hello! Thanks for putting this parser together. Really helpful. I have a question over something I don't quite understand yet. By reading the code I found out about the env variable `AOC_PLAYBACK` which I assume is something external to replay recorded games in order to parse record information. How does it work? How do I link this to the CLI so I can get the full information about a match?

Thank you for your help.

**Comment by happyleavesaoc** [comment]
Hi there, you're right, that is an external replay tool. Unfortunately it is not publicly available and only works for UserPatch 1.5 (not DE).

**Comment by zorrodg** [comment]
Is there any alternative you would recommend to perform a playback for DE matches, or rather any way to gather insights from a DE match from the record file?

**Comment by happyleavesaoc** [comment]
`aoc-mgz` can parse the recorded game file and provide quite a bit of information. This is of course different than playback, which involves memory access. There's no public alternative that I'm aware of.

**Comment by zorrodg** [comment]
Thank you for your insights!
