### ISSUE TITLE
What's the LICENSE of this project

### ISSUE THREAD

**Issue by hiiwave** [happyleavesaoc/aoc-mgz#59]
Hi @happyleavesaoc , thx for sharing this amazing repo!
As I didn't find a LICENSE file, I guessed you forgot to add it. Are you planning to [add a license](https://choosealicense.com/)? Thank you!

**Comment by happyleavesaoc** [comment]
MIT: https://github.com/happyleavesaoc/aoc-mgz/commit/fb506bbe749f52715dab2f32ce524fb1ba666a03
