### ISSUE TITLE
collections.Hashable -> collections.abc.Hashable

### ISSUE THREAD

**Issue by M1ngXU** [happyleavesaoc/aoc-mgz#84]
In [model.__init__.py|line351](https://github.com/happyleavesaoc/aoc-mgz/blob/5857d3c711cc4b02e4388df3223f50298c3643bf/mgz/model/__init__.py#L351), collections.Hashable needs to be replaced by collections.abc.Hashable.

**Comment by happyleavesaoc** [comment]
Fixed in https://github.com/happyleavesaoc/aoc-mgz/commit/6f42eb719f45882087ad64058bef891e0bee4491
