### ISSUE TITLE
How to merge two games that share a common point?

### ISSUE THREAD

**Issue by GeekyPeas** [happyleavesaoc/aoc-mgz#86]
I got redirected to your repository from a comment on this [Reddit AoE2 post: How to merge two recorded games in AoE2 DE that share a common point?](https://www.reddit.com/r/aoe2/comments/w17c9q/how_to_merge_two_recorded_games_in_aoe2_de_that/).

This is the problem that I am trying to solve:

Situation: We were playing a game and the game dropped. Then we restored the game. Now I have two recorded game: one before the drop and one after the restore.

Question: How can I merge the two records into one record?

Use-case: Actually I have many such recorded games that I have just manually renamed as part-1, part-2, part-3 etc... But in the end it becomes difficult to mannage. I wish I could merge them for some sanity.

I could install your package using `pip install mgz` and I could also run the [examples](https://github.com/happyleavesaoc/aoc-mgz#examples) in your `README.md`.

As mentioned in the reddit comment: your repository has [`merge` command](https://github.com/happyleavesaoc/aoc-mgz/blob/master/mgz/cli.py#L134) and I am very hopeful that it will solve my problem. However without accompanying documentation I am a little lost about where to begin and what to do. Can you please solve this for me?

Thanks! 

p.s.: Besides Reddit I have also asked this question [here](https://github.com/DavidEGrayson/aoe2recfun/issues/1) and [here](https://gaming.stackexchange.com/questions/398195/how-to-merge-two-recorded-games-in-aoe2-de-that-share-a-common-point).

**Comment by happyleavesaoc** [comment]
Merge is only supported for UserPatch. Could not get it to work for DE.
