### ISSUE TITLE
how do you generate minimaps?

### ISSUE THREAD

**Issue by lichifeng** [happyleavesaoc/aoc-mgz#89]
Sorry to bother, I'm author of aocrec.com, you did a real good job on aoe record parsing.

how do you generate minimaps? another package? not with this one?
and do you have a plan to document this project more detailed? really good job.

thx.

**Comment by TyrotoxismB** [comment]
@lichifeng you can use my service.
[Deasilsoft/a2j](https://github.com/Deasilsoft/a2j)

**Comment by lichifeng** [comment]
> 

nice. thanks.
