### ISSUE TITLE
AI learning from recordings

### ISSUE THREAD

**Issue by DjSapsan** [happyleavesaoc/aoc-mgz#94]
Hi. I want to try to make an AI that will learn from recordings. I've never worked with recs before. Where I can find more documentation/support/examples about this project that can help me? 
Also, if someone is interested, feel free to contact me in Discord - DjSapsan#4530

**Comment by M1ngXU** [comment]
Hi, i added you as a friend (lol)

**Comment by happyleavesaoc** [comment]
Lots of examples in the dependent project list: https://github.com/happyleavesaoc/aoc-mgz/network/dependents

**Comment by M1ngXU** [comment]
ok this is smart lol
